version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.5-node-browsers-legacy
      environment:
        RAILS_ENV: test
        POSTGRES_HOST: 127.0.0.1
    - image: circleci/postgres:12.1
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: db
    working_directory: ~/repo


    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run: yarn install

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run:
        name: Databasesetup
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    - run:
        name: Rubocop
        command: bundle exec rubocop
